apiVersion: v1
kind: Pod
metadata:
  name: malicious-cap
spec:
  containers:
  - name: busy
    image: busybox
    command: ["sh","-c","sleep 3600"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]