# scripts/deploy-violating-pod.sh
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: nginx-privileged
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      allowPrivilegeEscalation: true
      privileged: true
EOF
# → RECHAZADO POR GATEKEEPER